version: '3'
services:
  simple-snowplow:
    container_name: simple-snowplow
    build:
      context: simple_snowplow
      dockerfile: Dockerfile
    volumes:
    - ./simple_snowplow:/app
    ports:
    - "8000:80"
    environment:
    - "SNOWPLOW_COMMON__DEMO=true"
    restart: on-failure
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80", "--reload", "--log-level", "info"]
    depends_on:
    - clickhouse

  clickhouse:
    container_name: simple-snowplow-ch
    image: clickhouse/clickhouse-server:24.6.2.17
    environment:
    - "ALLOW_EMPTY_PASSWORD=yes"
    ports:
    - "8123:8123"
    - "9000:9000"
    - "9009:9009"
