version: '3'
services:
  simple-snowplow:
    container_name: snowplow
    image: vladenisov/simple-snowplow:latest
    ports:
    - "8000:80"
    environment:
    - "SNOWPLOW_COMMON__DEMO=true"
    restart: on-failure
    depends_on:
    - clickhouse

  clickhouse:
    image: clickhouse/clickhouse-server:25.3.2.39-alpine
    environment:
    - "CLICKHOUSE_PASSWORD=password"
    ports:
    - "8123:8123"
    - "9000:9000"
    - "9009:9009"
