version: '3'
services:
  simple-snowplow:
    container_name: snowplow
    image: vladenisov/simple-snowplow:0.0.1
    ports:
      - "8000:80"
    restart: on-failure
    depends_on:
      - clickhouse

  clickhouse:
    container_name: clickhouse
    image: yandex/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
