[common]
service_name = "simple-snowplow"
database = "clickhouse"
demo = false
[common.snowplow.schemas]
user_data = "iglu:dev.snowplow.simple/user_data"
page_data = "iglu:dev.snowplow.simple/page_data"
screen_data = "iglu:dev.snowplow.simple/screen_data"
ad_data = "iglu:dev.snowplow.simple/ad_data"

[elastic_apm]
enabled = false

[prometheus]
enabled = false

[clickhouse]
[clickhouse.connection]
url = "http://clickhouse:8123"
user = "default"
database = "default"
password = ""
[clickhouse.connection.bulk]
enabled = false
url = "http://clickhouse-bulk:8124"
[clickhouse.configuration]
database = "snowplow"
cluster_name = ""
[clickhouse.configuration.tables.local]
name = ""
engine = "MergeTree()"
order_by = "app_id, time, page, event_type, device_id, cityHash64(device_id), session_id"
[clickhouse.configuration.tables.distributed]
name = ""
[clickhouse.configuration.tables.buffer]
name = ""
enabled = false  # currently not supported
