[common]
service_name = "simple-snowplow"
database = "clickhouse"
demo = false
[common.snowplow.schemas]
user_data = "iglu:dev.snowplow.simple/user_data"
page_data = "iglu:dev.snowplow.simple/page_data"
screen_data = "iglu:dev.snowplow.simple/screen_data"
ad_data = "iglu:dev.snowplow.simple/ad_data"

[elastic_apm]
enabled = false

[prometheus]
enabled = false

[clickhouse]
[clickhouse.connection]
url = "http://clickhouse:8123"
user = "default"
[clickhouse.configuration]
database = "snowplow"
cluster_name = ""
engine = "MergeTree()"
[clickhouse.configuration.tables_names]
local = ""
distributed = ""
