[common]
service_name = "simple-snowplow"
database = "clickhouse"
debug = false

[elastic_apm]
enabled = false

[prometheus]
enabled = false

[clickhouse]
[clickhouse.connection]
url = "http://clickhouse:8123"
user = "default"
[clickhouse.configuration]
database = "snowplow"
cluster_name = ""
engine = "MergeTree()"
