[common]
service_name = "simple-snowplow"
database = "clickhouse"
demo = false
hostname = "http://localhost:8000"
[common.snowplow.schemas]
user_data = "dev.snowplow.simple/user_data"
page_data = "dev.snowplow.simple/page_data"
screen_data = "dev.snowplow.simple/screen_data"
ad_data = "dev.snowplow.simple/ad_data"
u2s_data = "dev.snowplow.simple/u2s_data"
[common.snowplow.endpoints]
post_endpoint = "/tracker"
get_endpoint = "/i"
proxy_endpoint = "/proxy"

[proxy]
domains = [
    "google-analytics.com",
    "www.googletagmanager.com"
]
paths = [
    "analytics.js",
    "gtm.js"
]

[logging]
json = false
level = "WARNING"

[elastic_apm]
enabled = false

[prometheus]
enabled = false

[clickhouse]
[clickhouse.connection]
interface = "http"
host = "clickhouse"
port = 8123
username = "default"
database = "default"
password = ""
[clickhouse.configuration]
database = "snowplow"
cluster_name = ""
[clickhouse.configuration.tables.local]
name = "local"
engine = "MergeTree()"
order_by = "app, platform, app_id, toDate(time), event_type, page, device_id, cityHash64(device_id), session_id, time"
[clickhouse.configuration.tables.distributed]
name = ""
[clickhouse.configuration.tables.buffer]
name = ""
enabled = false  # currently not supported
