table_fields = [
    {"column_name": "app_id", "payload_name": "aid"},
    {"column_name": "platform", "payload_name": "p"},
    {"column_name": "app", "payload_name": ("app_version", "app_build")},
    {"column_name": "page", "payload_name": "url"},
    {"column_name": "referer", "payload_name": "refr"},
    {"column_name": "event_type", "payload_name": "e"},
    {"column_name": "event_id", "payload_name": "eid"},
    {"column_name": "view_id", "payload_name": "view_id"},
    {"column_name": "session_id", "payload_name": "sid"},
    {"column_name": "visit_count", "payload_name": "vid"},
    {
        "column_name": "session",
        "payload_name": (
            "event_index",
            "previous_session_id",
            "first_event_id",
            "first_event_time",
            "storage_mechanism",
            "session_unstructured",
        ),
    },
    {
        "column_name": "amp",
        "payload_name": (
            "amp_device_id",
            "amp_client_id",
            "amp_session_id",
            "amp_visit_count",
            "amp_session_engaged",
            "amp_first_event_time",
            "amp_previous_session_time",
            "amp_view_id",
        ),
    },
    {"column_name": "device_id", "payload_name": "duid"},
    {"column_name": "user_id", "payload_name": "uid"},
    {"column_name": "time", "payload_name": "rtm"},
    {"column_name": "time_extra", "payload_name": ("dtm", "stm")},
    {"column_name": "timezone", "payload_name": "tz"},
    {"column_name": "title", "payload_name": "page"},
    {
        "column_name": "screen",
        "payload_name": (
            "screen_type",
            "screen_vc",
            "screen_tvc",
            "screen_activity",
            "screen_fragment",
            "screen_unstructured",
        ),
    },
    {"column_name": "page_data", "payload_name": "page_data"},
    {"column_name": "user_data", "payload_name": "user_data"},
    {"column_name": "user_ip", "payload_name": "user_ip"},
    {"column_name": "geolocation", "payload_name": "geolocation"},
    {"column_name": "user_agent", "payload_name": "user_agent"},
    {
        "column_name": "browser",
        "payload_name": (
            "browser_family",
            "browser_version_string",
            "cookie",
            "cs",
            "cd",
            "browser_unstructured",
        ),
    },
    {
        "column_name": "os",
        "payload_name": ("os_family", "os_version_string", "lang"),
    },
    {
        "column_name": "device",
        "payload_name": ("device_brand", "device_model"),
    },
    {"column_name": "device_is", "payload_name": "device_is"},
    {
        "column_name": "device_extra",
        "payload_name": (
            "carrier",
            "network_type",
            "network_technology",
            "open_idfa",
            "apple_idfa",
            "apple_idfv",
            "android_idfa",
            "battery_level",
            "battery_state",
            "low_power_mode",
        ),
    },
    {"column_name": "resolution", "payload_name": ("res", "vp", "ds")},
    {
        "column_name": "event",
        "payload_name": ("se_ac", "se_ca", "se_la", "se_pr", "se_va", "ue"),
    },
    {"column_name": "extra", "payload_name": "extra"},
    {"column_name": "tracker", "payload_name": ("tv", "tna")},
]
